name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6' # Ejecución automática semanal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@6749b872e89b3c10d213a6e599a7424584c1fa10
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}